### ISSUE TITLE
Any screenshots or demo?

### ISSUE THREAD

**Issue by alexbagirov** [chipbell4/Judge#79]

**Comment by chipbell4** [comment]
Hi @alexbagirov !
Hopefully, the resolution's good enough for you to get an idea of how the site looks and works. Let me know if you've got any questions.

![judgepage](https://cloud.githubusercontent.com/assets/2642329/9705455/2a7dd7a2-5493-11e5-9211-3d821e913e22.jpg)
![scoreboard](https://cloud.githubusercontent.com/assets/2642329/9705453/2a7a37fa-5493-11e5-9482-7a32daaf544f.jpg)
![teammessages](https://cloud.githubusercontent.com/assets/2642329/9705454/2a7c2e02-5493-11e5-9cdb-7b954f94e42e.jpg)
![teamsubmissions](https://cloud.githubusercontent.com/assets/2642329/9705452/2a79f844-5493-11e5-97c3-12a6dbb8e079.jpg)

**Comment by alexbagirov** [comment]
And one more question. How does it compile solutions? I can't see any scripts there.

**Comment by chipbell4** [comment]
Currently it does not judge from within. Instead it provides a zip file to download for manual judging. In general, it was easier to do it that way, rather than write judging scripts. I originally had a judging client, but I haven't really maintained it, since it was just as easy to eyeball the execution.

If you've got some ideas for automation, I'd love to hear them.
